
[sqlconfig]
	addr = "127.0.0.1:3306"
	dsn = "root:123456@tcp(127.0.0.1:3306)/shiji?timeout=10000s&readTimeout=10000s&writeTimeout=10000s&parseTime=true&loc=Local&charset=utf8mb4,utf8"
#	readDSN = ["{user}:{password}@tcp(127.0.0.2:3306)/{database}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8mb4,utf8","{user}:{password}@tcp(127.0.0.3:3306)/{database}?timeout=1s&readTimeout=1s&writeTimeout=1s&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
	active = 20
	idle = 10
	idleTimeout ="40h"
	queryTimeout = "200000ms"
	execTimeout = "300000ms"
	tranTimeout = "400000ms"
